title: Seun Ogunjobi
logo: data_logo.jpg
description: A data analyst with 2 years experience adept with the use of Excel for data automation, SQL for data manipulation and exploration and Powerbi for data visualizations and business intelligence
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
